### ISSUE TITLE
CasinocoinAPI Beginners guide fails on first script

### ISSUE THREAD

**Issue by cscchat** [casinocoin/casinocoin-dev-portal#2]
Using Node 4.2.1, after following the steps up to [Running the script](https://casinocoin.org/build/tutorial-casinocoinapi-beginners-guide.html#running-the-script) , I get the following error.
````
/Users/xxxx/Code/my_casinocoin_experiment/node_modules/casinocoin-libjs/node_modules/casinocoin-libjs-address-codec/src/x-address-codec.js:58
    const {
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/xxxx/Code/my_casinocoin_experiment/node_modules/babel-cli/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/xxxx/Code/my_casinocoin_experiment/node_modules/casinocoin-libjs/node_modules/casinocoin-libjs-address-codec/src/index.js:4:18)
    at Module._compile (module.js:435:26)
````

I tried to use babel-preset-env (since babel-preset-es2015 is deprecated), but no dice.  Additionally, I tried to use node v5.0.0 and got the same result.

I tried with node v8.14, and got a different error.

````
/Users/xxxx/Code/my_casinocoin_experiment/node_modules/casinocoin-libjs/dist/npm/common/schema-validator.js:60
        throw new ValidationError(result.errors.join());
        ^
[ValidationError(instance additionalProperty "port" exists in instance when not allowed)]
    at ValidationError.CasinocoinError (/Users/xxxx/Code/my_casinocoin_experiment/node_modules/casinocoin-libjs/dist/npm/common/errors.js:36:19)
    at new ValidationError (/Users/xxxx/Code/my_casinocoin_experiment/node_modules/casinocoin-libjs/dist/npm/common/errors.js:180:119)
    at Object.schemaValidate (/Users/xxxx/Code/my_casinocoin_experiment/node_modules/casinocoin-libjs/dist/npm/common/schema-validator.js:60:15)
    at Object.wrapper [as apiOptions] (/Users/xxxx/Code/my_casinocoin_experiment/node_modules/casinocoin-libjs/node_modules/lodash/index.js:3592:19)
    at new CasinocoinAPI (/Users/xxxx/Code/my_casinocoin_experiment/node_modules/casinocoin-libjs/dist/npm/api.js:103:25)
    at Object.<anonymous> (/Users/xxxx/Code/my_casinocoin_experiment/get-account-info.js:4:13)
    at Module._compile (module.js:569:30)
    at loader (/Users/xxxx/Code/my_casinocoin_experiment/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/xxxx/Code/my_casinocoin_experiment/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
````

I did not `npm install` between versions (if that makes a difference, let me know).

I also tried using `npx babel` instead of `./node_modules/.bin/babel-node` as recommend on the babeljs.io site.  no change.

**Comment by cscchat** [comment]
So, after looking into this further, destructuring is not supported in Node 4/5.  Support was begun in Node 6.

Unfortunately, `casinocoin-libjs-address-codec/src/x-address-codec.js` uses destructuring, and babel is only transpiling the current file, so it breaks.

The two ways I could see to deal with this are:

1. requiring Node 6+ in the examples
2. transpiling the code in the repositiories to be compliant with Node 5

Given that Node 8.11 is the current recommended LTS, I would suggest updating the docs to reflect that.

**Comment by ajochems** [comment]
Good point. Wallet (which uses this lib) is using Node 8.9.3 LTS so we need to update the docs to reflect that requirement

**Comment by cscchat** [comment]
Also, using Node 8.x+ removes the requirement for babel, unless we need to support ES2018 in our scripts.  Might be nice to simplify things, unless we plan on using those features in the docs.
